### ISSUE TITLE
第一个例子就过不去啊

### ISSUE THREAD

**Issue by BESTLyc** [name5566/leaf#154]
gate\internal\module.go:26:3: cannot use msg.Processor (type json.Processor) as type network.Processor in field value:
        json.Processor does not implement network.Processor (Marshal method has pointer receiver)

第一个例子把默认的 msg.Processor的改成了 json.Processor，但是gate下面定义的Processor是network.Processor

**Comment by kokais** [comment]
我这边没问题，network.Processor是一个interface，json.Processor实现了那些方法就没问题的

2019/04/12 17:13:24 [release] Leaf 1.1.3 starting up
2019/04/12 17:13:24 [debug  ] run 
2019/04/12 17:13:24 [debug  ] run

**Comment by cnx7** [comment]
第一个例子就会报错

**Comment by cnx7** [comment]
第一个例子就报错了

```
2019/06/15 21:36:47 [release] Leaf 1.1.3 starting up

2019/06/15 21:36:52 [error  ] interface conversion: *msg.Hello is not gate.Agent: missing method Close: goroutine 5 [running]:
github.com/name5566/leaf/chanrpc.(*Server).exec.func1(0xc000054df8, 0xc00012c0a0, 0xc0000223c0)
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/chanrpc/chanrpc.go:104 +0xc4
panic(0x12fb300, 0xc000090210)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
server/game/internal.handleHello(0xc00000e420, 0x2, 0x2)
	/Users/cnx7/Projects/GoProject/leafserver/src/server/game/internal/handler.go:22 +0x70
github.com/name5566/leaf/chanrpc.(*Server).exec(0xc00012c0a0, 0xc0000223c0, 0x0, 0x0)
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/chanrpc/chanrpc.go:117 +0x2a3
github.com/name5566/leaf/chanrpc.(*Server).Exec(0xc00012c0a0, 0xc0000223c0)
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/chanrpc/chanrpc.go:131 +0x39
github.com/name5566/leaf/module.(*Skeleton).Run(0xc0001100a0, 0xc000080070)
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/module/skeleton.go:59 +0x238
github.com/name5566/leaf/module.run(0xc0000b8ab0)
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/module/module.go:54 +0x3c
created by github.com/name5566/leaf/module.Init
	/Users/cnx7/Projects/GoProject/leafserver/src/github.com/name5566/leaf/module/module.go:40 +0xa3
2019/06/15 21:36:52 [debug  ] read message: EOF
```

**Comment by 0990** [comment]
例子没问题，要使用json.NewProcessor()，你上面用错了
